2019-12-10 00:26:06,011 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0de0f10a58>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:26:12,025 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ebb390>, 'Connection to 122.50.5.146 timed out. (connect timeout=5)')
2019-12-10 00:26:18,041 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ebb978>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 00:26:24,057 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ec5eb8>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 00:26:30,074 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ebb240>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 00:27:04,872 - __main__ - ERROR - Timeout Error
2019-12-10 00:27:21,814 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0f10ef0>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 00:27:27,831 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ebb470>, 'Connection to 94.51.83.2 timed out. (connect timeout=5)')
2019-12-10 00:27:33,847 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ecb080>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 00:27:39,864 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ecb320>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 00:28:01,846 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ecb898>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 00:28:19,996 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0de0ecb940>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:28:40,185 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ed6cc0>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 00:29:10,718 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ecb0f0>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 00:29:16,734 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ebb470>, 'Connection to 81.182.164.40 timed out. (connect timeout=5)')
2019-12-10 00:29:29,862 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ed6ef0>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 00:29:35,879 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ecb9b0>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 00:45:06,030 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7ff7f008e4a8>, 'Connection to 177.21.224.73 timed out. (connect timeout=5)')
2019-12-10 00:45:10,761 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff7f008eb00>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:45:40,282 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff7f00a7940>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:45:46,298 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7ff7f008e7b8>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 00:46:35,921 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bdeac8>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 00:46:41,938 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfa278>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 00:46:43,021 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c00b38>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:47:10,675 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfad68>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 00:47:11,757 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c00748>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:47:13,079 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2bfab00>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:47:31,128 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 00:47:37,730 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c00240>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:47:43,746 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfad68>, 'Connection to 213.109.129.56 timed out. (connect timeout=5)')
2019-12-10 00:48:13,314 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2bfaf60>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:48:33,607 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00a20>, 'Connection to 81.182.164.40 timed out. (connect timeout=5)')
2019-12-10 00:49:16,402 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfa898>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 00:49:22,419 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00ac8>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 00:49:37,322 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00630>, 'Connection to 94.51.83.2 timed out. (connect timeout=5)')
2019-12-10 00:49:38,633 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2bfa898>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:49:57,201 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00a20>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 00:50:12,927 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2bfab00>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:50:14,251 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c17ba8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:50:20,266 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c50d30>, 'Connection to 81.17.150.122 timed out. (connect timeout=5)')
2019-12-10 00:50:21,597 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c00668>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:50:27,611 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfa4e0>, 'Connection to 177.21.224.73 timed out. (connect timeout=5)')
2019-12-10 00:50:39,094 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c170f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:50:40,446 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c004a8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:50:49,891 - __main__ - ERROR - ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))
2019-12-10 00:50:55,907 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfa828>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 00:51:10,898 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c17400>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:51:23,766 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00940>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 00:51:29,783 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c50dd8>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 00:51:47,526 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfa208>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 00:52:12,305 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c004e0>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 00:52:55,673 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00668>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 00:53:48,150 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c172e8>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 00:53:54,166 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00710>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 00:54:00,557 - __main__ - ERROR - ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))
2019-12-10 00:54:06,573 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bdef28>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
